name: CI

on:
  push:
    tags: ["*"]
    branches-ignore:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd dependency_bazelizer && bazel test //... && cd -
      - run: cd dependency_bazelizer && bazel run //src:dependency-bazelizer -- -if ./tests/ci_inputs/deb_packages.in -cf ./tests/ci_inputs/s3_config.json -if ./tests/ci_inputs/deb_packages_2.in && cd -
      - run: cd dependency_bazelizer && bazel run //src:dependency-bazelizer -- -if ./tests/ci_inputs/deb_packages.in -cf ./tests/ci_inputs/s3_config.json && cd -
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  build-and-run-demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd demo_module && bazel run //:dependency-bazelizer && cd -
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
