name: CI

on:
  push:
    tags: ["*"]
  pull_request:
  workflow_dispatch:

jobs:
  bazel-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: bazel test //...

  run-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: bazel run //src:dependency-bazelizer -- -if ./tests/ci_inputs/deb_packages.in -cf ./tests/ci_inputs/storage_config.json -if ./tests/ci_inputs/deb_packages_2.in
      - run: bazel run //src:dependency-bazelizer -- -if ./tests/ci_inputs/deb_packages.in -cf ./tests/ci_inputs/unknown_storage_config.json
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  run-example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd example && bazel run //:dependency-bazelizer -- -if ../tests/ci_inputs/deb_packages.in -cf ../tests/ci_inputs/storage_config.json -if ../tests/ci_inputs/deb_packages_2.in
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}